### ISSUE TITLE
URL in setup.py is incorrect

### ISSUE THREAD

**Issue by adamlwgriffiths** [JonathanPorta/pyscrape#8]
setup.py
`url='https://github.com/jonathanporta/pyscraper',`

This returns a 404, the URL should have the 'r' taken off the end.

**Comment by JonathanPorta** [comment]
Thanks for pointing this out. I renamed the repo and forgot to update it. This project is very much a WIP and isn't even really to a working prototype yet. But, hopefully we'll be there soon.
